name: ci
on:
  push:
    branches:
      - main
      - +([0-9])?(.{+([0-9]),x}).x
  pull_request:

jobs:
  release:
    name: Release
    if: ${{ github.repository == 'pkfln/spaceship-arch-section' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout Repo
        uses: actions/checkout@v2

      - name: 🚀 Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            semantic-release-license
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
